architect:
- yegor256
- dmarkov
install:
- sudo gem install --no-ri --no-rdoc pdd
- sudo gem install --no-ri --no-rdoc est
docker:
  image: yegor256/jcabi-aether
assets:
  secring.gpg: zerocracy/home#assets/secring.gpg
  settings.xml: zerocracy/home#assets/jcabi/settings.xml
  pubring.gpg: zerocracy/home#assets/pubring.gpg
  s3cfg: zerocracy/home#assets/s3cfg
merge:
  script: |-
    mvn clean install site -Psite -Pqulice --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=/dev/null
    est --dir=est --file=/dev/null
  commanders:
  - carlosmiranda
  - darkled
  - dmzaytsev
  - ggajos
  - hdouss
  - krzyk
  - longtimeago
  - mkordas
  - pinaf
deploy:
  script: |-
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=jcabi-aether.xml
    s3cmd --no-progress put jcabi-aether.xml --config=../s3cfg s3://pdd.teamed.io/jcabi-aether.xml
    est --dir=./est --verbose --file=jcabi-aether.xml --format=xml
    s3cmd --no-progress put jcabi-aether.xml --config=../s3cfg s3://est.teamed.io/jcabi-aether.xml
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pqulice -Psonatype -Pjcabi --errors --settings ../settings.xml
    mvn clean site-deploy -Psite --errors --settings ../settings.xml
  commanders:
  - yegor256